// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmhovnhlbymvndxamymd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtaG92bmhsYnltdm5keGFteW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjMyNzgsImV4cCI6MjA2NTkzOTI3OH0.90UJKTYzkPaOrzyJ7c85dU4XDAFbNUkJv4x6yj4fmiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);